-- Criar tabela de investimentos
CREATE TABLE IF NOT EXISTS public.investimentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    tipo TEXT NOT NULL, -- Poupança, CDB, Tesouro Direto, etc.
    valor_atual NUMERIC(15, 2) DEFAULT 0.00 NOT NULL,
    descricao TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS (Row Level Security)
ALTER TABLE public.investimentos ENABLE ROW LEVEL SECURITY;

-- Criar políticas
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Usuários podem ver seus próprios investimentos') THEN
        CREATE POLICY "Usuários podem ver seus próprios investimentos" ON public.investimentos FOR SELECT USING (auth.uid() = user_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Usuários podem inserir seus próprios investimentos') THEN
        CREATE POLICY "Usuários podem inserir seus próprios investimentos" ON public.investimentos FOR INSERT WITH CHECK (auth.uid() = user_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Usuários podem atualizar seus próprios investimentos') THEN
        CREATE POLICY "Usuários podem atualizar seus próprios investimentos" ON public.investimentos FOR UPDATE USING (auth.uid() = user_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Usuários podem excluir seus próprios investimentos') THEN
        CREATE POLICY "Usuários podem excluir seus próprios investimentos" ON public.investimentos FOR DELETE USING (auth.uid() = user_id);
    END IF;
END $$;
